# Generated by Django 5.0.6 on 2024-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('major', models.CharField(choices=[('IT', 'B.Sc.CSIT'), ('CE', 'Computer Engineer'), ('Civ_E', 'Civil Engineer'), ('Ele_E', 'Electronic Engineer')], max_length=20)),
            ],
        ),
    ]
